# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: napari.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='napari.proto',
  package='napari_rpc.protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnapari.proto\x12\x11napari_rpc.protos\"U\n\x07NdArray\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\x0c\n\x04\x61xes\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\x0f\n\x07spacing\x18\x04 \x03(\x01\x12\r\n\x05\x61rray\x18\x05 \x01(\x0c\"\xdd\x03\n\x0f\x41\x64\x64ImageRequest\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.napari_rpc.protos.NdArray\x12\x19\n\x0c\x63hannel_axis\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x0b\n\x03rgb\x18\x03 \x03(\x08\x12\x10\n\x08\x63olormap\x18\x04 \x03(\t\x12\x17\n\x0f\x63ontrast_limits\x18\x05 \x03(\x01\x12\r\n\x05gamma\x18\x06 \x03(\x01\x12\x15\n\rinterpolation\x18\x07 \x03(\t\x12\x11\n\trendering\x18\x08 \x03(\t\x12\x15\n\riso_threshold\x18\t \x03(\x01\x12\x13\n\x0b\x61ttenuation\x18\n \x03(\x01\x12\x0c\n\x04name\x18\x0b \x03(\t\x12\r\n\x05scale\x18\x0c \x03(\x01\x12\x11\n\ttranslate\x18\r \x03(\x01\x12\x0e\n\x06rotate\x18\x0e \x03(\x01\x12\r\n\x05shear\x18\x0f \x03(\x01\x12\x0e\n\x06\x61\x66\x66ine\x18\x10 \x03(\x01\x12\x0f\n\x07opacity\x18\x11 \x03(\x01\x12\x10\n\x08\x62lending\x18\x12 \x03(\t\x12\x0f\n\x07visible\x18\x13 \x03(\x08\x12\x17\n\nmultiscale\x18\x14 \x01(\x08H\x01\x88\x01\x01\x12\x12\n\x05\x63\x61\x63he\x18\x15 \x01(\x08H\x02\x88\x01\x01\x42\x0f\n\r_channel_axisB\r\n\x0b_multiscaleB\x08\n\x06_cache\"<\n\tIsOkReply\x12\x11\n\thas_error\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2X\n\x06Napari\x12N\n\x08\x41\x64\x64Image\x12\".napari_rpc.protos.AddImageRequest\x1a\x1c.napari_rpc.protos.IsOkReply\"\x00\x62\x06proto3'
)




_NDARRAY = _descriptor.Descriptor(
  name='NdArray',
  full_name='napari_rpc.protos.NdArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='napari_rpc.protos.NdArray.dtype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axes', full_name='napari_rpc.protos.NdArray.axes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='napari_rpc.protos.NdArray.shape', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spacing', full_name='napari_rpc.protos.NdArray.spacing', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array', full_name='napari_rpc.protos.NdArray.array', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=120,
)


_ADDIMAGEREQUEST = _descriptor.Descriptor(
  name='AddImageRequest',
  full_name='napari_rpc.protos.AddImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='napari_rpc.protos.AddImageRequest.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_axis', full_name='napari_rpc.protos.AddImageRequest.channel_axis', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rgb', full_name='napari_rpc.protos.AddImageRequest.rgb', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colormap', full_name='napari_rpc.protos.AddImageRequest.colormap', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contrast_limits', full_name='napari_rpc.protos.AddImageRequest.contrast_limits', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='napari_rpc.protos.AddImageRequest.gamma', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interpolation', full_name='napari_rpc.protos.AddImageRequest.interpolation', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rendering', full_name='napari_rpc.protos.AddImageRequest.rendering', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iso_threshold', full_name='napari_rpc.protos.AddImageRequest.iso_threshold', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attenuation', full_name='napari_rpc.protos.AddImageRequest.attenuation', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='napari_rpc.protos.AddImageRequest.name', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='napari_rpc.protos.AddImageRequest.scale', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translate', full_name='napari_rpc.protos.AddImageRequest.translate', index=12,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotate', full_name='napari_rpc.protos.AddImageRequest.rotate', index=13,
      number=14, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shear', full_name='napari_rpc.protos.AddImageRequest.shear', index=14,
      number=15, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affine', full_name='napari_rpc.protos.AddImageRequest.affine', index=15,
      number=16, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opacity', full_name='napari_rpc.protos.AddImageRequest.opacity', index=16,
      number=17, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blending', full_name='napari_rpc.protos.AddImageRequest.blending', index=17,
      number=18, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visible', full_name='napari_rpc.protos.AddImageRequest.visible', index=18,
      number=19, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multiscale', full_name='napari_rpc.protos.AddImageRequest.multiscale', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cache', full_name='napari_rpc.protos.AddImageRequest.cache', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_channel_axis', full_name='napari_rpc.protos.AddImageRequest._channel_axis',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_multiscale', full_name='napari_rpc.protos.AddImageRequest._multiscale',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cache', full_name='napari_rpc.protos.AddImageRequest._cache',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=123,
  serialized_end=600,
)


_ISOKREPLY = _descriptor.Descriptor(
  name='IsOkReply',
  full_name='napari_rpc.protos.IsOkReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_error', full_name='napari_rpc.protos.IsOkReply.has_error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='napari_rpc.protos.IsOkReply.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='napari_rpc.protos.IsOkReply._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=602,
  serialized_end=662,
)

_ADDIMAGEREQUEST.fields_by_name['data'].message_type = _NDARRAY
_ADDIMAGEREQUEST.oneofs_by_name['_channel_axis'].fields.append(
  _ADDIMAGEREQUEST.fields_by_name['channel_axis'])
_ADDIMAGEREQUEST.fields_by_name['channel_axis'].containing_oneof = _ADDIMAGEREQUEST.oneofs_by_name['_channel_axis']
_ADDIMAGEREQUEST.oneofs_by_name['_multiscale'].fields.append(
  _ADDIMAGEREQUEST.fields_by_name['multiscale'])
_ADDIMAGEREQUEST.fields_by_name['multiscale'].containing_oneof = _ADDIMAGEREQUEST.oneofs_by_name['_multiscale']
_ADDIMAGEREQUEST.oneofs_by_name['_cache'].fields.append(
  _ADDIMAGEREQUEST.fields_by_name['cache'])
_ADDIMAGEREQUEST.fields_by_name['cache'].containing_oneof = _ADDIMAGEREQUEST.oneofs_by_name['_cache']
_ISOKREPLY.oneofs_by_name['_error'].fields.append(
  _ISOKREPLY.fields_by_name['error'])
_ISOKREPLY.fields_by_name['error'].containing_oneof = _ISOKREPLY.oneofs_by_name['_error']
DESCRIPTOR.message_types_by_name['NdArray'] = _NDARRAY
DESCRIPTOR.message_types_by_name['AddImageRequest'] = _ADDIMAGEREQUEST
DESCRIPTOR.message_types_by_name['IsOkReply'] = _ISOKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NdArray = _reflection.GeneratedProtocolMessageType('NdArray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'napari_pb2'
  # @@protoc_insertion_point(class_scope:napari_rpc.protos.NdArray)
  })
_sym_db.RegisterMessage(NdArray)

AddImageRequest = _reflection.GeneratedProtocolMessageType('AddImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDIMAGEREQUEST,
  '__module__' : 'napari_pb2'
  # @@protoc_insertion_point(class_scope:napari_rpc.protos.AddImageRequest)
  })
_sym_db.RegisterMessage(AddImageRequest)

IsOkReply = _reflection.GeneratedProtocolMessageType('IsOkReply', (_message.Message,), {
  'DESCRIPTOR' : _ISOKREPLY,
  '__module__' : 'napari_pb2'
  # @@protoc_insertion_point(class_scope:napari_rpc.protos.IsOkReply)
  })
_sym_db.RegisterMessage(IsOkReply)



_NAPARI = _descriptor.ServiceDescriptor(
  name='Napari',
  full_name='napari_rpc.protos.Napari',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=664,
  serialized_end=752,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddImage',
    full_name='napari_rpc.protos.Napari.AddImage',
    index=0,
    containing_service=None,
    input_type=_ADDIMAGEREQUEST,
    output_type=_ISOKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAPARI)

DESCRIPTOR.services_by_name['Napari'] = _NAPARI

# @@protoc_insertion_point(module_scope)
