# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import napari_pb2 as napari__pb2


class NapariStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddImage = channel.unary_unary(
                '/napari_rpc.protos.Napari/AddImage',
                request_serializer=napari__pb2.AddImageRequest.SerializeToString,
                response_deserializer=napari__pb2.IsOkReply.FromString,
                )


class NapariServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NapariServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddImage,
                    request_deserializer=napari__pb2.AddImageRequest.FromString,
                    response_serializer=napari__pb2.IsOkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'napari_rpc.protos.Napari', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Napari(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/napari_rpc.protos.Napari/AddImage',
            napari__pb2.AddImageRequest.SerializeToString,
            napari__pb2.IsOkReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
